export type FieldType =
  | "string"
  | "integer"
  | "number"
  | "boolean"
  | "date"
  | "datetime";

export interface FieldDefinition {
    name: string;
    type: FieldType;
    required: boolean;
    unique: boolean;
    nullable: boolean;

    minLength?: number;
    maxLength?: number,
    defaultValue?: string | number | boolean;

    autoGenerated?: "createdAt" | "updatedAt"
}