import type { EntityDefinition } from "@backend-file-generator/shared";

export function generateValidationSchema(
  entity: EntityDefinition
): string {
  const createFields = entity.fields
    .filter(
      (field) =>
        field.name !== entity.primaryKey &&
        !field.autoGenerated
    )
    .map((field) => {
      let schema = "";

      switch (field.type) {
        case "string":
          schema = "z.string()";
          break;

        case "integer":
          schema = "z.number().int()";
          break;

        case "number":
          schema = "z.number()";
          break;

        case "boolean":
          schema = "z.boolean()";
          break;

        case "date":
        case "datetime":
          schema = "z.coerce.date()";
          break;

        default:
          throw new Error(
            `Unsupported field type: ${field.type}`
          );
      }

      if (field.minLength !== undefined) {
        schema += `.min(${field.minLength})`;
      }

      if (field.maxLength !== undefined) {
        schema += `.max(${field.maxLength})`;
      }

      if (field.nullable) {
        schema += ".nullable()";
      } else if (!field.required) {
        schema += ".optional()";
      }

      return `  ${field.name}: ${schema}`;
    });

  const updateFields = entity.fields
    .filter(
      (field) =>
        field.name !== entity.primaryKey &&
        !field.autoGenerated
    )
    .map((field) => {
      let schema = "";

      switch (field.type) {
        case "string":
          schema = "z.string()";
          break;

        case "integer":
          schema = "z.number().int()";
          break;

        case "number":
          schema = "z.number()";
          break;

        case "boolean":
          schema = "z.boolean()";
          break;

        case "date":
        case "datetime":
          schema = "z.coerce.date()";
          break;

        default:
          throw new Error(
            `Unsupported field type: ${field.type}`
          );
      }

      if (field.minLength !== undefined) {
        schema += `.min(${field.minLength})`;
      }

      if (field.maxLength !== undefined) {
        schema += `.max(${field.maxLength})`;
      }

      if (field.nullable) {
        schema += ".nullable()";
      }

      schema += ".optional()";

      return `  ${field.name}: ${schema}`;
    });

  return `import { z } from "zod";

export const ${entity.name}CreateSchema = z.object({
${createFields.join(",\n")}
});

export const ${entity.name}UpdateSchema = z.object({
${updateFields.join(",\n")}
});

export type ${entity.name}CreateInput = z.infer<
  typeof ${entity.name}CreateSchema
>;

export type ${entity.name}UpdateInput = z.infer<
  typeof ${entity.name}UpdateSchema
>;
`;
}